import os
import re
from pathlib import Path

# Add peer folder to search path
import sys
sys.path.append(str(Path(__file__).resolve().parent / "audit"))
from validate_metadata import parse_header

# Title mapping for each of the 9 standard folders
FOLDER_TITLES = {
    "01-product": "Product Overview & Strategy",
    "02-user-guide": "End User & Operations Guides",
    "03-admin-guide": "Administration & Custodian Guides",
    "04-installation": "Installation & Setup Guides",
    "05-developer": "Developer & Integration Guides",
    "06-api": "API Reference Specifications",
    "07-kb": "Knowledge Base & Troubleshooting",
    "08-architecture": "Architecture Specifications & Proposals",
    "09-release-notes": "Release Notes & Sprint Reports"
}

def get_sort_key(item):
    id_val = item["id"]
    match = re.match(r'([A-Z]+)\-(\d+)', id_val)
    if match:
        return (match.group(1), int(match.group(2)))
    return ("ZZZ", id_val)

def generate_indexes():
    # Resolve docs root directory (parent of tools)
    tools_dir = Path(__file__).resolve().parent
    docs_dir = tools_dir.parent
    
    target_folders = sorted(list(FOLDER_TITLES.keys()))
    index_data = []

    # 1. Parse all Markdown files in target folders
    for folder in target_folders:
        folder_path = docs_dir / folder
        if not folder_path.exists():
            continue
        for file in os.listdir(folder_path):
            if file.endswith(".md") and file != "index.md":
                file_path = folder_path / file
                rel_path = file_path.relative_to(docs_dir).as_posix()
                
                # Default fallback metadata
                doc_id = "N/A"
                title = file
                audience = "N/A"
                module = "Core"
                owner = "N/A"
                status = "Active"
                version = "1.0.0"
                last_updated = "2026-06-25"
                
                try:
                    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                        content = f.read()
                    
                    meta = parse_header(content)
                    if meta:
                        doc_id = meta.get("Document ID", doc_id)
                        title = meta.get("Title", title)
                        audience = meta.get("Audience", audience)
                        module = meta.get("Module", module)
                        owner = meta.get("Owner", owner)
                        status = meta.get("Status", status)
                        version = meta.get("Version", version)
                        last_updated = meta.get("Last Updated", last_updated)
                except Exception as e:
                    print(f"Warning: Could not parse metadata for {rel_path}: {e}")
                
                index_data.append({
                    "id": doc_id,
                    "title": title,
                    "folder": folder,
                    "filename": file,
                    "audience": audience,
                    "module": module,
                    "owner": owner,
                    "status": status,
                    "version": version,
                    "last_updated": last_updated,
                    "rel_path": rel_path
                })

    # Sort index data by prefix and document ID number
    index_data.sort(key=get_sort_key)

    # 2. Write the root DOCUMENTATION_INDEX.md file
    root_index_path = docs_dir / "DOCUMENTATION_INDEX.md"
    with open(root_index_path, 'w', encoding='utf-8') as f:
        f.write("# SMRITI Master Documentation Index\n\n")
        f.write("Version: 1.0.1  \n")
        f.write("Author: Jawahar R. Mallah, Founder & Chief Architect, AITDL  \n")
        f.write("Status: Active  \n")
        f.write("Last Audited: 2026-06-30  \n\n")
        f.write("> [!NOTE]\n")
        f.write("> This is the Single Source of Truth (SSOT) document registry for the SMRITI Retail OS project.\n")
        f.write("> Every documentation file must be registered here. This file is automatically generated.\n\n")
        f.write("## Document Registry\n\n")
        f.write("| Document ID | Title | Folder | Audience | Module | Owner | Status | Version | Last Updated |\n")
        f.write("| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
        for item in index_data:
            # Generate a repository-relative link (relative to the docs root)
            link = f"[{item['id']}](./{item['rel_path']})"
            f.write(f"| {link} | {item['title']} | `{item['folder']}` | {item['audience']} | {item['module']} | {item['owner']} | {item['status']} | {item['version']} | {item['last_updated']} |\n")

    print(f"Master index generated at: {root_index_path.relative_to(docs_dir.parent)} with {len(index_data)} entries.")

    # 3. Generate folder index.md files for each of the 9 directories
    for folder in target_folders:
        folder_docs = [item for item in index_data if item["folder"] == folder]
        folder_index_path = docs_dir / folder / "index.md"
        title = FOLDER_TITLES.get(folder, folder.replace("-", " ").title())
        
        with open(folder_index_path, 'w', encoding='utf-8') as f:
            f.write(f"# {title}\n\n")
            f.write(f"Welcome to the **{title}** documentation set. Below is the list of available documents in this section:\n\n")
            f.write("| Document ID | Title | Audience | Module | Owner | Status | Last Updated |\n")
            f.write("| --- | --- | --- | --- | --- | --- | --- |\n")
            for doc in folder_docs:
                # Relative link is simple: just the file name since it is in the same directory
                link = f"[{doc['id']}](./{doc['filename']})"
                f.write(f"| {link} | {doc['title']} | {doc['audience']} | {doc['module']} | {doc['owner']} | {doc['status']} | {doc['last_updated']} |\n")
        
        print(f"Folder index generated at: {folder_index_path.relative_to(docs_dir.parent)}")

if __name__ == "__main__":
    generate_indexes()
